### PR TITLE
make it clean code and disable right click

### PR DESCRIPTION
**Pull request by masdzub**
Hi Harry, I want to contribute again. 
Updating some scripts and making the clean code 🙏🏼

### CODE REVIEW

**Review by harsxv — CHANGES_REQUESTED** [review]
Dockerfile: would be more clean if you can remove the `./` after each files
Can you please addressed this first before I will merged?

**Review by harsxv — CHANGES_REQUESTED** [review]
I don’t think it’s necessary to disable right-click

**Comment by masdzub** [comment]
Hi Harry, it's done. please try check it again.

**Comment by harsxv** [comment]
Neat, thank you!

**Pull request merged**
