### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by arioch**
Had some trouble getting it to run on a distro with an out-of-date Python version (below 3.7), so I whipped up a quick Dockerfile.

### CODE REVIEW

**Comment by harsxv** [comment]
Thanks for adding Dockerfile.

Can you please look for a smaller Docker image? I tried building it, and 1GB feels a bit too large. Especially since it’s called TinyStatus, it might be better to keep it tiny! :)

```
❯ docker images | grep tinystatus
tinystatus                 latest            8a1f3e9d77d1   15 minutes ago   1.04GB
```

**Comment by arioch** [comment]
That actually makes a whole lot of sense.
[9f1e7a5](https://github.com/harsxv/tinystatus/pull/5/commits/9f1e7a51ea590a99b57175265a52c8d8ed5e7c88) should fix that:

```
docker images | grep tinystatus
tinystatus   latest    66b405189bd5   2 minutes ago   148MB
```

**Comment by harsxv** [comment]
I prefer using python:3-alpine instead. It works like a charm as well, let's goo :)

```
❯ head -n 1 Dockerfile
FROM python:3-alpine
❯ docker images | grep tinystatus
tinystatus                 latest            e7140299b6a3   4 hours ago     80.3MB
```

**Comment by arioch** [comment]
Down to 74MB on my machine... ✨ 
```
docker images | grep tinystatus
tinystatus   latest    5250287a8a34   2 minutes ago   74.5MB
```

**Comment by harsxv** [comment]
Well done! Merged ✅
Thank you for contributing 👍🏽

**Pull request merged**
